# Generated by Django 3.1.5 on 2021-01-29 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetWordCloud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_tweet_timestamp', models.DateTimeField(db_index=True, null=True)),
                ('last_tweet_timestamp', models.DateTimeField(db_index=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('words', models.TextField(help_text='comma separated words from tweeter given a specific hashtag and a timespan')),
            ],
        ),
    ]
